---
title: "Lab2"
author: "SAF"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part I: Introduction to modeling using basic R syntax

*Congratulations, you have puppy fever! As someone who is inflicted with puppy 
fever, you would like to buy as many puppies as you perceivable can. To help 
you determine if you can afford all of the puppies you want or to determine 
how many puppies you can afford, you opt to use R to help you. In this 
exercise, please print the contents of each variable after you declare it.*

**Integer:** *puppies* variable holds the number of puppies you’d like to have.
```{R Part 1a, echo=FALSE}
puppies <- 12L
cat("puppies =", puppies)
```

**Integer:** *max_puppies* variable holds Qty of puppies you can afford for $1,000.
```{R Part 1b, echo=FALSE}
max_puppies <- 1L
cat("max_puppies =", max_puppies)
```

**Numeric:** *puppy_price* variable holds the price of a single puppy.
```{R Part 1c, echo=FALSE}
puppy_price <- 01.01
cat("puppy_price =", puppy_price)
```

**Numeric:** *total_cost* variable holds the total price of all puppies.
```{R Part 1d, echo=FALSE}
total_cost <- 01.01
cat("total_cost =", total_cost)
```

**Logical-Bool** *too_expensive* Variables return TRUE if the cost is greater than $1,000.
```{R Part 1e, echo=FALSE}
too_expensive <- 1L
BoolResult <- too_expensive > 1000L
cat("too_expensive=", BoolResult)
```

# Part II: Manipulating variables and learning how to use new functions

You work as a data analyst for a new company and are asked to create id tags for 
everyone at work. Your goal is to make it informative as well as personal to 
help facilitate collaboration in the work place.To do this, you first want to 
gather information about each employee.

**2a.Character** *my_name* This assigns your name to the variable.
Assign *my_name* to a variable in (4) different ways.
```{R Part 2a, echo=FALSE}
message("-----------------------------------------------------------------------------------")
my_name <- "Sal F"
print(my_name)
message(my_name)
my_name
cat(my_name, "\n\n")
```


**2b.Character** *favorite_day* holds your favorite day of the week.
```{R Part 2b, echo=FALSE}
message("-----------------------------------------------------------------------------------")
favorite_day <- "Thursday"
cat("My favorite day is:", favorite_day)
```


**2c.Integer** *my_height* Assigns your height in whole inche values.
```{R Part 2c, echo=FALSE}
message("-----------------------------------------------------------------------------------")
my_height <- 71L
cat("My height is:",my_height,"inche/s")
```


**2d.Characters** *favorite_quote* Holds your favorite quote.
```{R Part 2d, echo=FALSE}
message("-----------------------------------------------------------------------------------")
favorite_quote <- "Whiskey is for drinking; water is for fighting over."
count <- nchar(favorite_quote)

cat("My favorite qoute is about water: ", favorite_quote, "It has",count,"characters.")
```


**2e.Type of Data Objects** Verify what type *my_name*, *my_height*, *favorite_day*, and *favorite_quote* are.
```{R Part 2e, echo=FALSE}
message("-----------------------------------------------------------------------------------")
cat("my_name type is a", typeof(my_name))
    
cat("favorite_day type is a", typeof(favorite_day))

cat("my_height type is an", typeof(my_height))

cat("favorite_qoute type is a", typeof(favorite_quote))

```


**2f.Coerce these variables** to a *numeric* and describe what happens.
```{R Part 2f, echo=FALSE}
message("-----------------------------------------------------------------------------------")
cat("my_name as a numeric:", as.numeric(my_name))

cat("favorite_day as numeric:", as.numeric(favorite_day))

cat("my_height as numeric:", as.numeric(my_height))

cat("favorite_qoute as numeric:\n", as.numeric(favorite_quote))
```

**2g.Create of Vector** named "id" that contains *my_name, my_height, favorite_day,* and *favorite_quote*.
```{R Part 2g, echo=FALSE}
message("-----------------------------------------------------------------------------------")
id <- c(my_name, my_height, favorite_day, favorite_quote)
cat("id vector: ",id)
```

**2h.Class of Vector** What class is "id"? Did the classes change for the variables themselves?
```{R Part 2h, echo=FALSE}
message("-----------------------------------------------------------------------------------")
cat("The vector id is a type of:\n", typeof(id))
message("Below are the data types for each variable. Verfiy if variables weren't altered")
cat("my_name type:", typeof(my_name))
cat("favorite_day type:", typeof(favorite_day))
cat("my_height type:", typeof(my_height))
cat("favorite_qoute type:", typeof(favorite_quote))
```

**2i.Employee's Information** Your employer wants you to be able to print each employee’s id while displaying each variable of information line by line. As a beginner with R, however, you are unfamiliar with how to do this so your employer gives you a hint to use the functions cat and paste.
Try using cat and paste with id as a function argument. How do the results differ?
What happens when we use cat and paste at the same time *(i.e. f(g(x)))*?
What happens if we change the order we use them *(i.e. g(f(x)))*?
```{R Part 2i, echo=FALSE}
message("-----------------------------------------------------------------------------------")
cat("cat function(id):",id, sep=", ", "\n")
message("-----------------------------------------------------------------------------------")
paste("paste function(id):",id, sep=", ")
message("-----------------------------------------------------------------------------------")
cat(paste(id))
message("-----------------------------------------------------------------------------------")
paste(cat(id))
message("-----------------------------------------------------------------------------------")
```


```{R Part 2 tmp, echo=FALSE}
message("-----------------------------------------------------------------------------------")

message("Try using cat and paste with id as a function argument. How do the results differ?")

message("What happens when we use cat and paste at the same time (i.e. f(g(x)))?")

message("What happens if we change the order we use them (i.e. g(f(x)))?")

message("How would you determine the difference between cat and paste using R documentation (from within RStudio)?")

message("What is a great internet resource to use as discussed in the book?")

message("What do sep and collapse arguments for paste do?")

message("If we wanted to append each character variable in our vector id with a new line (i.e. \\n) would we use sep or collapse?")

message("Display the contents of id using a combination of cat and paste with the appropriate arguments for paste.")

```


# Part III: Accessing data in GitHub and mastering order of operations

```{R Part 3, include=FALSE}
#Part 3: Accessing data in GitHub and mastering order of operations
#Your employer asks you to solve for x using the quadratic equation:



#The values for a, b, and c are the min, max, and mean respectively of a data set that your employer has on GitHub.

#In module 3, you were required to fork this repository to your GitHub and then clone it to your machine. To access the data set for determining a, b, and c we need to pull from the original repository onto our machine using GitHub. Before you can sync your fork with an upstream repository, however, you must configure a remote that points to the upstream repository. See LINK for help. After syncing, please click on data.RData in Module-4 to load the data set into your environment. Alternatively (and preferred), please use load followed by a character argument of the directory path to load the data set into your environment.

#Please calculate a (using min), b (using max), and c (using mean) from data. Pay careful attention to follow order of operations (PEMDAS)

#Use a, b, and c to solve for x using the quadratic equation. You will need to do this for + and - in the quadratic equation (i.e. you should have TWO answers). Please display the answer as x = {x1, x2} using cat and paste. In part 2 we used paste to display the contents of a vector, here we use it to concatenate different vaariables into one expression.

#Example of how to use paste

#section <- 165
#date <- Sys.Date()
#cat(paste("We are taking CSIT_", section, "and today is", date, "!\n"))
## We are taking CSIT_ 165 and today is 2022-01-17 !
```
